//样式配置
const THEME_COLOR = "#333333";
const THEME_COLOR_DISABLE = "#e6e6e6";
const THEME_COLOR_WHITE = "#ffffff";
const THEME_COLOR_BORDER = "#cccccc";
const BUTTON_PRESS_COLOR = "#222222";



//项目配置
const BASE_INTERFACE = "http://192.168.1.106:8088/api/";


export {
	//样式配置
	THEME_COLOR,
	THEME_COLOR_DISABLE,
	THEME_COLOR_WHITE,
	BUTTON_PRESS_COLOR,
	THEME_COLOR_BORDER,
	
	//项目配置
	BASE_INTERFACE
};